version: "3"
services:
    home-assistant:
        container_name: homeassistant
        privileged: true
        restart: unless-stopped
        environment:
            - PUID=1004
            - PGID=1006
            - TZ=US/Mountain
        volumes:
            - ./hass/config:/config
            - /run/dbus:/run/dbus:ro
        network_mode: host
        image: ghcr.io/home-assistant/home-assistant:stable
#-------------------------------------  
    piper:  
      image: homeassistant/amd64-addon-piper:latest  
      container_name: piper  
      environment:
        - PUID=1004
        - PGID=1006
        - TZ=US/Mountain
      entrypoint: python3  	
      command: >		
        -m wyoming_piper  
        --piper '/usr/share/piper/piper'  
        --uri 'tcp://0.0.0.0:10200'  
        --length-scale "1"  
        --noise-scale "0.667"  
        --speaker "0"
        --debug  
        --voice en_US-lessac-medium
        --max-piper-procs "1"  
        --data-dir /data  
        --data-dir /share/piper  
        --download-dir /data  
      ports:  
        - "10200:10200"  
      volumes:  
        - ./piper-data:/data  
      restart: unless-stopped  
  
#----------------------------------------  
    whisper:  
      image: homeassistant/amd64-addon-whisper:latest  
      container_name: whisper  
      environment:
          - PUID=1004
          - PGID=1006
          - TZ=US/Mountain     
      entrypoint: python3  
      command: >  
        -m wyoming_faster_whisper  
        --uri tcp://0.0.0.0:10300  
        --model small-int8  
        --beam-size 1  
        --language en  
        --data-dir /data  
        --download-dir /data  
      ports:  
        - "10300:10300"  
      volumes:  
        - ./whisper-data:/data  
      restart: unless-stopped

